### ISSUE TITLE
Listing deployable projects returns an empty list

### ISSUE THREAD

**Issue by heyvito** [d3estudio/giskard-deploy#1]
And also yields a really nice error:

```
 TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at generateTree (/app/bot_modules/giskard-deploy/src/giskarddeploy.js:68:26)
    at Projects.find.exec.then.arr (/app/bot_modules/giskard-deploy/src/giskarddeploy.js:242:55)
    at newTickHandler (/app/node_modules/mpromise/lib/promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by heyvito** [comment]
Caused by an extra `console.log` call. Fixed by 71d51d6
